version: '3.8'

services:
  app:
    build: .
    container_name: facial_app
    ports:
      - "5000:5000"
    depends_on:
      - facial_db
  facial_db:
    image: mysql:8
    container_name: facial_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: facial_recognition
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"  # Map le port local 8080 au port du conteneur
    environment:
      PMA_HOST: facial_db  # Relie PhpMyAdmin à MariaDB
      PMA_USER: root
      PMA_PASSWORD: password

volumes:
  mysql_data:


