version: '3.8'

services:
  app:
    build: .
    container_name: facial_app
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: facial_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: facial_recognition
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
