version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: facial_recognition_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://user:password@db:5432/facial_recognition
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:14
    container_name: facial_recognition_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: facial_recognition
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
